version: '3'
services:
  solid:
    container_name: solidjs
    build: .
    depends_on:
      - app

  app:
    container_name: flask
    build: ./app
    environment:
      - FLASK_ENV=production

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    environment:
      - CERTBOT_EMAIL=jiechenmc@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./prod_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - solid
      - app

volumes:
  nginx_secrets:
