version: '3'
services:
  solid:
    container_name: solidjs
    build: .
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - .:/client

  app:
    container_name: flask
    build: ./app
    environment:
      - FLASK_ENV=development
